package com.founder.mapper.phbdb;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.founder.mapper.base.BaseMapper;
import com.founder.rhip.ehr.entity.clinic.OutpatientInfo;

@Repository("msOutpatientInfoMapper")
public interface MsOutpatientInfoMapper extends BaseMapper<OutpatientInfo> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMSDBTEST.MS_OUTPATIENT_INFO
     *
     * @mbggenerated Wed Jul 23 14:01:14 CST 2014
     */
    int countByExample(MsOutpatientInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMSDBTEST.MS_OUTPATIENT_INFO
     *
     * @mbggenerated Wed Jul 23 14:01:14 CST 2014
     */
    int deleteByExample(MsOutpatientInfoExample example);

    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMSDBTEST.MS_OUTPATIENT_INFO
     *
     * @mbggenerated Wed Jul 23 14:01:14 CST 2014
     */
    List<OutpatientInfo> selectByExample(MsOutpatientInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMSDBTEST.MS_OUTPATIENT_INFO
     *
     * @mbggenerated Wed Jul 23 14:01:14 CST 2014
     */
    int updateByExampleSelective(@Param("record") OutpatientInfo record, @Param("example") MsOutpatientInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMSDBTEST.MS_OUTPATIENT_INFO
     *
     * @mbggenerated Wed Jul 23 14:01:14 CST 2014
     */
    int updateByExample(@Param("record") OutpatientInfo record, @Param("example") MsOutpatientInfoExample example);
}