package com.founder.mapper.mdmdb;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.founder.mapper.base.BaseMapper;
import com.founder.rhip.ehr.entity.basic.PersonInfo;

@Repository("biPersonInfoMapper")
public interface BiPersonInfoMapper extends BaseMapper<PersonInfo>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEIDDBTEST.BI_PERSON_INFO
     *
     * @mbggenerated Tue Jul 22 14:00:06 CST 2014
     */
    int countByExample(BiPersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEIDDBTEST.BI_PERSON_INFO
     *
     * @mbggenerated Tue Jul 22 14:00:06 CST 2014
     */
    int deleteByExample(BiPersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEIDDBTEST.BI_PERSON_INFO
     *
     * @mbggenerated Tue Jul 22 14:00:06 CST 2014
     */
    int deleteByPrimaryKey(Long id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEIDDBTEST.BI_PERSON_INFO
     *
     * @mbggenerated Tue Jul 22 14:00:06 CST 2014
     */
    List<PersonInfo> selectByExample(BiPersonInfoExample example);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEIDDBTEST.BI_PERSON_INFO
     *
     * @mbggenerated Tue Jul 22 14:00:06 CST 2014
     */
    int updateByExampleSelective(@Param("record") PersonInfo record, @Param("example") BiPersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEIDDBTEST.BI_PERSON_INFO
     *
     * @mbggenerated Tue Jul 22 14:00:06 CST 2014
     */
    int updateByExample(@Param("record") PersonInfo record, @Param("example") BiPersonInfoExample example);

}