package com.founder.rhip.ehr.repository.ism;

import javax.annotation.Resource;

import org.springframework.jdbc.core.simple.SimpleJdbcTemplate;
import org.springframework.stereotype.Repository;

import com.founder.fasf.beans.Criteria;
import com.founder.fasf.beans.Page;
import com.founder.fasf.beans.PageList;
import com.founder.fasf.repository.AbstractDao;
import com.founder.fasf.repository.SqlBuilder;
import com.founder.fasf.util.StringUtil;
import com.founder.rhip.ehr.entity.ism.ReportInfo;
import com.founder.rhip.ehr.entity.management.DmDiseaseInfo;
import com.founder.rhip.ehr.entity.management.DmReportInfo;

/**
 * @author liuk
 *
 */
@Repository("isReportInfoDao")
public class ReportInfoDaoImpl extends AbstractDao<ReportInfo, Long> implements IReportInfoDao {
	
	@Resource(name = "phbdbJDBCTemplate")
	private SimpleJdbcTemplate simpleJdbcTemplate;

	@Override
	public PageList<ReportInfo> getRepeatCardList(Page page, Criteria criteria,String conditions) {
//		if (null == criteria) {
//			criteria = new Criteria();
//		}
//		StringBuilder sql = new StringBuilder();
//		sql.append(" SELECT DM_REPORT_INFO.CDM_ID,DM_REPORT_INFO.ID,DM_PERSON_INFO.NAME,DM_PERSON_INFO.GENDER,DM_PERSON_INFO.IDCARD,DM_PERSON_INFO.BIRTHDAY,DM_REPORT_INFO.DIS_TYPE,DM_REPORT_INFO.CREATE_ORGAN_NAME,DM_REPORT_INFO.CREATE_DATE,CDM_STATUS_INFO.REPORT_STATUS,DM_REPORT_INFO.PERSON_ID " +
//				" FROM DM_REPORT_INFO INNER JOIN DM_PERSON_INFO ON DM_REPORT_INFO.DM_PERSON_ID=DM_PERSON_INFO.ID LEFT JOIN CDM_STATUS_INFO ON DM_REPORT_INFO.CDM_ID=CDM_STATUS_INFO.ID INNER JOIN ");
//		if(StringUtil.isNotEmpty(conditions)){
//			if(conditions.equals("1")){
//				sql.append( " ( SELECT DM_PERSON_INFO.NAME,DM_REPORT_INFO.DIS_TYPE,DM_REPORT_INFO.SUB_DIS_TYPE FROM DM_REPORT_INFO INNER JOIN DM_PERSON_INFO ON DM_REPORT_INFO.DM_PERSON_ID=DM_PERSON_INFO.ID LEFT JOIN CDM_STATUS_INFO ON DM_REPORT_INFO.CDM_ID=CDM_STATUS_INFO.ID WHERE CDM_STATUS_INFO.REPORT_STATUS!=5  GROUP BY DM_PERSON_INFO.NAME,DM_REPORT_INFO.DIS_TYPE,DM_REPORT_INFO.SUB_DIS_TYPE   HAVING COUNT(1)>1 ) A  " +
//						"   ON DM_PERSON_INFO.NAME=A.NAME AND DM_REPORT_INFO.DIS_TYPE=A.DIS_TYPE AND DM_REPORT_INFO.SUB_DIS_TYPE=A.SUB_DIS_TYPE  AND CDM_STATUS_INFO.REPORT_STATUS!=5 ");
//			}else if(conditions.equals("2")){
//				sql.append( " ( SELECT DM_PERSON_INFO.BIRTHDAY,DM_REPORT_INFO.DIS_TYPE,DM_REPORT_INFO.SUB_DIS_TYPE FROM DM_REPORT_INFO INNER JOIN DM_PERSON_INFO ON DM_REPORT_INFO.DM_PERSON_ID=DM_PERSON_INFO.ID LEFT JOIN CDM_STATUS_INFO ON DM_REPORT_INFO.CDM_ID=CDM_STATUS_INFO.ID WHERE CDM_STATUS_INFO.REPORT_STATUS!=5  GROUP BY DM_PERSON_INFO.BIRTHDAY,DM_REPORT_INFO.DIS_TYPE,DM_REPORT_INFO.SUB_DIS_TYPE   HAVING COUNT(1)>1 ) A  " +
//						"   ON  DM_PERSON_INFO.BIRTHDAY=A.BIRTHDAY AND DM_REPORT_INFO.DIS_TYPE=A.DIS_TYPE AND DM_REPORT_INFO.SUB_DIS_TYPE=A.SUB_DIS_TYPE  AND CDM_STATUS_INFO.REPORT_STATUS!=5 ");
//			}else{
//				sql.append( " ( SELECT DM_PERSON_INFO.NAME,DM_PERSON_INFO.BIRTHDAY,DM_REPORT_INFO.DIS_TYPE,DM_REPORT_INFO.SUB_DIS_TYPE FROM DM_REPORT_INFO INNER JOIN DM_PERSON_INFO ON DM_REPORT_INFO.DM_PERSON_ID=DM_PERSON_INFO.ID LEFT JOIN CDM_STATUS_INFO ON DM_REPORT_INFO.CDM_ID=CDM_STATUS_INFO.ID WHERE CDM_STATUS_INFO.REPORT_STATUS!=5  GROUP BY DM_PERSON_INFO.NAME,DM_PERSON_INFO.BIRTHDAY,DM_REPORT_INFO.DIS_TYPE,DM_REPORT_INFO.SUB_DIS_TYPE   HAVING COUNT(1)>1 ) A  " +
//						"   ON DM_PERSON_INFO.NAME=A.NAME AND DM_PERSON_INFO.BIRTHDAY=A.BIRTHDAY AND DM_REPORT_INFO.DIS_TYPE=A.DIS_TYPE AND DM_REPORT_INFO.SUB_DIS_TYPE=A.SUB_DIS_TYPE  AND CDM_STATUS_INFO.REPORT_STATUS!=5 ");
//			}
//			
//		}else{
//			sql.append( " ( SELECT DM_PERSON_INFO.NAME,DM_PERSON_INFO.BIRTHDAY,DM_REPORT_INFO.DIS_TYPE,DM_REPORT_INFO.SUB_DIS_TYPE FROM DM_REPORT_INFO INNER JOIN DM_PERSON_INFO ON DM_REPORT_INFO.DM_PERSON_ID=DM_PERSON_INFO.ID   LEFT JOIN CDM_STATUS_INFO ON DM_REPORT_INFO.CDM_ID=CDM_STATUS_INFO.ID WHERE CDM_STATUS_INFO.REPORT_STATUS!=5 GROUP BY DM_PERSON_INFO.NAME,DM_PERSON_INFO.BIRTHDAY,DM_REPORT_INFO.DIS_TYPE,DM_REPORT_INFO.SUB_DIS_TYPE   HAVING COUNT(1)>1 ) A  " +
//					"   ON DM_PERSON_INFO.NAME=A.NAME AND DM_PERSON_INFO.BIRTHDAY=A.BIRTHDAY AND DM_REPORT_INFO.DIS_TYPE=A.DIS_TYPE AND DM_REPORT_INFO.SUB_DIS_TYPE=A.SUB_DIS_TYPE  AND CDM_STATUS_INFO.REPORT_STATUS!=5 ");
//		}
//			
//		SqlBuilder.buildWhereStatement(DmDiseaseInfo.class, sql, criteria);
//	    SqlBuilder.buildOrderStatement(sql, "DM_PERSON_INFO.NAME,DM_REPORT_INFO.CREATE_DATE DESC");
//		return this.getPageList(page, sql.toString(), criteria);
		return null;
	}
}