
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.founder.rhip.cdm.service.ws;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2017-05-12T13:39:46.925+08:00
 * Generated source version: 2.6.0
 * 
 */

@WebService(
                      serviceName = "ExamCountWebserviceService2",
                      portName = "ExamCountWebservice2Port",
                      targetNamespace = "http://web.medexa.founder.com/",
                      wsdlLocation = "examCountservice2.wsdl",
                      endpointInterface = "com.founder.rhip.cdm.service.ws.IExamCountWebservice2")
                      
public class IExamCountWebservice2Impl implements IExamCountWebservice2 {

    private static final Logger LOG = Logger.getLogger(IExamCountWebservice2Impl.class.getName());

    /* (non-Javadoc)
     * @see com.founder.medexa.web.IExamCountWebservice2#findExamCount(java.lang.String  dateBegin ,)java.lang.String  dateEnd )*
     */
    public java.util.List<ExamDataInfo> findExamCount(String dateBegin, String dateEnd) {
        LOG.info("Executing operation findExamCount");
        System.out.println(dateBegin);
        System.out.println(dateEnd);
        try {
            java.util.List<ExamDataInfo> _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
