package com.founder.rhip.cdm.service.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2017-05-12T13:39:46.940+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://web.medexa.founder.com/", name = "IExamCountWebservice2")
@XmlSeeAlso({ObjectFactory.class})
public interface IExamCountWebservice2 {

    @WebMethod
    @RequestWrapper(localName = "findExamCount", targetNamespace = "http://web.medexa.founder.com/", className = "com.founder.medexa.web.FindExamCount")
    @ResponseWrapper(localName = "findExamCountResponse", targetNamespace = "http://web.medexa.founder.com/", className = "com.founder.medexa.web.FindExamCountResponse")
    @WebResult(name = "ExamCountInfo", targetNamespace = "")
    public java.util.List<ExamDataInfo> findExamCount(
            @WebParam(name = "dateBegin", targetNamespace = "")
                    String dateBegin,
            @WebParam(name = "dateEnd", targetNamespace = "")
                    String dateEnd
    );
}
