
package com.founder.rhip.cdm.service.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2017-05-12T13:39:46.855+08:00
 * Generated source version: 2.6.0
 * 
 */
public final class IExamCountWebservice2_ExamCountWebservice2Port_Client {

    private static final QName SERVICE_NAME = new QName("http://web.medexa.founder.com/", "ExamCountWebserviceService2");

    private IExamCountWebservice2_ExamCountWebservice2Port_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ExamCountWebserviceService2.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ExamCountWebserviceService2 ss = new ExamCountWebserviceService2(wsdlURL, SERVICE_NAME);
        IExamCountWebservice2 port = ss.getExamCountWebservice2Port();
        
        {
        System.out.println("Invoking findExamCount...");
        String _findExamCount_dateBegin = "2013-01-12";
        String _findExamCount_dateEnd = "2017-01-12";
        java.util.List<ExamDataInfo> _findExamCount__return = port.findExamCount(_findExamCount_dateBegin, _findExamCount_dateEnd);
        System.out.println("findExamCount.result=" + _findExamCount__return);


        }

        System.exit(0);
    }

}
